#!/usr/bin/perl
use utf8;

print "Enter a circle's radius: ";
chomp($radius = <STDIN>);
$circunference = 2 * 3.141592654 * $radius;
print "The circunference of a circle with a radius of $radius is $circunference\n";