#!/usr/bin/perl
use 5.014;
use warnings;
use utf8;

sub greet {
	my($person) = @_;
	state $last_person;
	print "Hi $person. ";
	if (defined $last_person) {
		print "$last_person is also here!\n";
	} else {
		print "You are the first one here!\n";		
	}
	$last_person = $person;
}

&greet("Fred");
&greet("Barney");
&greet("Wilma");